//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vnpost_ocr_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInfo
    {
        public long ContactInfoID { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string PostalDistrictCode { get; set; }
        public string Street { get; set; }
        public Nullable<int> PersonalPaperTypeID { get; set; }
        public string PersonalPaperNumber { get; set; }
        public Nullable<System.DateTime> PersonalPaperIssuedDate { get; set; }
        public string PersonalPaperIssuedPlace { get; set; }
        public long CustomerID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual PersonalPaperType PersonalPaperType { get; set; }
        public virtual District District { get; set; }
    }
}
