//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vnpost_ocr_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirebaseToken
    {
        public long ID { get; set; }
        public string FirebaseToken1 { get; set; }
        public long AuthTokenID { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual AuthenticationToken AuthenticationToken { get; set; }
    }
}
