//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vnpost_ocr_system.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VNPOST_AppointmentEntities : DbContext
    {
        public VNPOST_AppointmentEntities()
            : base("name=VNPOST_AppointmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<AdminRole> AdminRoles { get; set; }
        public virtual DbSet<API> APIs { get; set; }
        public virtual DbSet<APIInputParam> APIInputParams { get; set; }
        public virtual DbSet<APIMethod> APIMethods { get; set; }
        public virtual DbSet<APIOutputParam> APIOutputParams { get; set; }
        public virtual DbSet<ContactInfo> ContactInfoes { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<EmailVerification> EmailVerifications { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderImage> OrderImages { get; set; }
        public virtual DbSet<OrderStatusDetail> OrderStatusDetails { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<PaymentStatu> PaymentStatus { get; set; }
        public virtual DbSet<PersonalPaperType> PersonalPaperTypes { get; set; }
        public virtual DbSet<PhoneVerification> PhoneVerifications { get; set; }
        public virtual DbSet<PostOffice> PostOffices { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<PublicAdministration> PublicAdministrations { get; set; }
        public virtual DbSet<ResetPasswordToken> ResetPasswordTokens { get; set; }
        public virtual DbSet<ServiceTimer> ServiceTimers { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<AuthenticationToken> AuthenticationTokens { get; set; }
    }
}
