//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vnpost_ocr_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationMessage
    {
        public long ID { get; set; }
        public long OrderID { get; set; }
        public string Title { get; set; }
        public string ContentText { get; set; }
        public System.DateTime SentDate { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
