//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vnpost_ocr_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatusDetail
    {
        public long OrderStatusDetailID { get; set; }
        public long OrderID { get; set; }
        public int StatusID { get; set; }
        public string Note { get; set; }
        public Nullable<long> PosCode { get; set; }
        public System.DateTime CreatedTime { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual PostOffice PostOffice { get; set; }
        public virtual Status Status { get; set; }
    }
}
