//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vnpost_ocr_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceTimer
    {
        public int ServiceTimeID { get; set; }
        public Nullable<int> ServiceTimeHour { get; set; }
        public Nullable<int> ServiceTimeMinute { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
